# Generated by Django 5.2.1 on 2025-06-04 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("futurelabsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "telegram_message_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID сообщения в Telegram",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        default="🚁", max_length=10, verbose_name="Эмодзи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-published_date"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kanatohod", "Комплексы канатоход"),
                    ("bas", "Многофункциональные БАС"),
                    ("fpv", "FPV-Дроны"),
                    ("cargo", "Грузовые дроны"),
                    ("software", "Программное обеспечение"),
                    ("champ", "Оборудование для чемпионатов"),
                ],
                help_text="Выберите категорию из списка",
                max_length=100,
                null=True,
                verbose_name="Категория",
            ),
        ),
    ]
