# Generated by Django 5.2.2 on 2025-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurelabsite', '0003_botwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='botwhitelist',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя пользователя (first_name)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botwhitelist',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия пользователя (last_name)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botwhitelist',
            name='username',
            field=models.CharField(blank=True, help_text='Имя пользователя (username)', max_length=255, null=True),
        ),
    ]
