# Generated by Django 5.2.1 on 2025-06-16 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurelabsite', '0004_botwhitelist_first_name_botwhitelist_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел характеристик',
                'verbose_name_plural': 'Разделы характеристик',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='futurelabsite.product', verbose_name='Продукт')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='futurelabsite.characteristicsection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
