# Generated by Django 5.2.1 on 2025-06-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futurelabsite', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/', verbose_name='Видео'),
        ),
    ]
